//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 10:12:17 AM CET 
//


package eu.gloria.rt.entity.scheduler.plan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for constraints complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="constraints">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="targets" type="{http://gloria.eu/rt/entity/scheduler/plan}targets"/>
 *         &lt;element name="mode" type="{http://gloria.eu/rt/entity/scheduler/plan}mode"/>
 *         &lt;element name="filters" type="{http://gloria.eu/rt/entity/scheduler/plan}filters"/>
 *         &lt;element name="tracking" type="{http://gloria.eu/rt/entity/scheduler/plan}trackingRateType" minOccurs="0"/>
 *         &lt;element name="notBeforeDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="notAfterDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="pointing-error" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="FoV" type="{http://gloria.eu/rt/entity/scheduler/plan}doubleIterval" minOccurs="0"/>
 *         &lt;element name="moonDistance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="moonAltitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="seeing" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="targetAltitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="FWHM" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pixelScale" type="{http://gloria.eu/rt/entity/scheduler/plan}doubleIterval" minOccurs="0"/>
 *         &lt;element name="exposureTime" type="{http://gloria.eu/rt/entity/scheduler/plan}positiveDoubleIterval" minOccurs="0"/>
 *         &lt;element name="readoutTime" type="{http://gloria.eu/rt/entity/scheduler/plan}positiveDouble" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "constraints", propOrder = {
    "targets",
    "mode",
    "filters",
    "tracking",
    "notBeforeDate",
    "notAfterDate",
    "pointingError",
    "foV",
    "moonDistance",
    "moonAltitude",
    "seeing",
    "targetAltitude",
    "fwhm",
    "pixelScale",
    "exposureTime",
    "readoutTime"
})
public class Constraints {

    @XmlElement(required = true)
    protected Targets targets;
    @XmlElement(required = true)
    protected Mode mode;
    @XmlElement(required = true)
    protected Filters filters;
    protected TrackingRateType tracking;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar notBeforeDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar notAfterDate;
    @XmlElement(name = "pointing-error")
    protected Double pointingError;
    @XmlElement(name = "FoV")
    protected DoubleIterval foV;
    protected Double moonDistance;
    protected Double moonAltitude;
    protected Double seeing;
    protected Double targetAltitude;
    @XmlElement(name = "FWHM")
    protected Double fwhm;
    protected DoubleIterval pixelScale;
    protected PositiveDoubleIterval exposureTime;
    protected Double readoutTime;

    /**
     * Gets the value of the targets property.
     * 
     * @return
     *     possible object is
     *     {@link Targets }
     *     
     */
    public Targets getTargets() {
        return targets;
    }

    /**
     * Sets the value of the targets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Targets }
     *     
     */
    public void setTargets(Targets value) {
        this.targets = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link Mode }
     *     
     */
    public Mode getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mode }
     *     
     */
    public void setMode(Mode value) {
        this.mode = value;
    }

    /**
     * Gets the value of the filters property.
     * 
     * @return
     *     possible object is
     *     {@link Filters }
     *     
     */
    public Filters getFilters() {
        return filters;
    }

    /**
     * Sets the value of the filters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filters }
     *     
     */
    public void setFilters(Filters value) {
        this.filters = value;
    }

    /**
     * Gets the value of the tracking property.
     * 
     * @return
     *     possible object is
     *     {@link TrackingRateType }
     *     
     */
    public TrackingRateType getTracking() {
        return tracking;
    }

    /**
     * Sets the value of the tracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrackingRateType }
     *     
     */
    public void setTracking(TrackingRateType value) {
        this.tracking = value;
    }

    /**
     * Gets the value of the notBeforeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNotBeforeDate() {
        return notBeforeDate;
    }

    /**
     * Sets the value of the notBeforeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNotBeforeDate(XMLGregorianCalendar value) {
        this.notBeforeDate = value;
    }

    /**
     * Gets the value of the notAfterDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNotAfterDate() {
        return notAfterDate;
    }

    /**
     * Sets the value of the notAfterDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNotAfterDate(XMLGregorianCalendar value) {
        this.notAfterDate = value;
    }

    /**
     * Gets the value of the pointingError property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPointingError() {
        return pointingError;
    }

    /**
     * Sets the value of the pointingError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPointingError(Double value) {
        this.pointingError = value;
    }

    /**
     * Gets the value of the foV property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleIterval }
     *     
     */
    public DoubleIterval getFoV() {
        return foV;
    }

    /**
     * Sets the value of the foV property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleIterval }
     *     
     */
    public void setFoV(DoubleIterval value) {
        this.foV = value;
    }

    /**
     * Gets the value of the moonDistance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMoonDistance() {
        return moonDistance;
    }

    /**
     * Sets the value of the moonDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMoonDistance(Double value) {
        this.moonDistance = value;
    }

    /**
     * Gets the value of the moonAltitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMoonAltitude() {
        return moonAltitude;
    }

    /**
     * Sets the value of the moonAltitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMoonAltitude(Double value) {
        this.moonAltitude = value;
    }

    /**
     * Gets the value of the seeing property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSeeing() {
        return seeing;
    }

    /**
     * Sets the value of the seeing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSeeing(Double value) {
        this.seeing = value;
    }

    /**
     * Gets the value of the targetAltitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTargetAltitude() {
        return targetAltitude;
    }

    /**
     * Sets the value of the targetAltitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTargetAltitude(Double value) {
        this.targetAltitude = value;
    }

    /**
     * Gets the value of the fwhm property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFWHM() {
        return fwhm;
    }

    /**
     * Sets the value of the fwhm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFWHM(Double value) {
        this.fwhm = value;
    }

    /**
     * Gets the value of the pixelScale property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleIterval }
     *     
     */
    public DoubleIterval getPixelScale() {
        return pixelScale;
    }

    /**
     * Sets the value of the pixelScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleIterval }
     *     
     */
    public void setPixelScale(DoubleIterval value) {
        this.pixelScale = value;
    }

    /**
     * Gets the value of the exposureTime property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveDoubleIterval }
     *     
     */
    public PositiveDoubleIterval getExposureTime() {
        return exposureTime;
    }

    /**
     * Sets the value of the exposureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveDoubleIterval }
     *     
     */
    public void setExposureTime(PositiveDoubleIterval value) {
        this.exposureTime = value;
    }

    /**
     * Gets the value of the readoutTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getReadoutTime() {
        return readoutTime;
    }

    /**
     * Sets the value of the readoutTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setReadoutTime(Double value) {
        this.readoutTime = value;
    }

}
