//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 10:12:17 AM CET 
//


package eu.gloria.rt.entity.scheduler.plan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for coordinates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coordinates">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="J2000" type="{http://gloria.eu/rt/entity/scheduler/plan}J2000"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coordinates", propOrder = {
    "j2000"
})
public class Coordinates {

    @XmlElement(name = "J2000")
    protected J2000 j2000;

    /**
     * Gets the value of the j2000 property.
     * 
     * @return
     *     possible object is
     *     {@link J2000 }
     *     
     */
    public J2000 getJ2000() {
        return j2000;
    }

    /**
     * Sets the value of the j2000 property.
     * 
     * @param value
     *     allowed object is
     *     {@link J2000 }
     *     
     */
    public void setJ2000(J2000 value) {
        this.j2000 = value;
    }

}
