//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 10:12:17 AM CET 
//


package eu.gloria.rt.entity.scheduler.plan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for J2000 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="J2000">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RA" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="DEC" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "J2000", propOrder = {
    "ra",
    "dec"
})
public class J2000 {

    @XmlElement(name = "RA")
    protected double ra;
    @XmlElement(name = "DEC")
    protected double dec;

    /**
     * Gets the value of the ra property.
     * 
     */
    public double getRA() {
        return ra;
    }

    /**
     * Sets the value of the ra property.
     * 
     */
    public void setRA(double value) {
        this.ra = value;
    }

    /**
     * Gets the value of the dec property.
     * 
     */
    public double getDEC() {
        return dec;
    }

    /**
     * Sets the value of the dec property.
     * 
     */
    public void setDEC(double value) {
        this.dec = value;
    }

}
