//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 10:12:17 AM CET 
//


package eu.gloria.rt.entity.scheduler.plan;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.gloria.rt.entity.scheduler.plan package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.gloria.rt.entity.scheduler.plan
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Expose }
     * 
     */
    public Expose createExpose() {
        return new Expose();
    }

    /**
     * Create an instance of {@link Window }
     * 
     */
    public Window createWindow() {
        return new Window();
    }

    /**
     * Create an instance of {@link Loop }
     * 
     */
    public Loop createLoop() {
        return new Loop();
    }

    /**
     * Create an instance of {@link Plan }
     * 
     */
    public Plan createPlan() {
        return new Plan();
    }

    /**
     * Create an instance of {@link Binning }
     * 
     */
    public Binning createBinning() {
        return new Binning();
    }

    /**
     * Create an instance of {@link J2000 }
     * 
     */
    public J2000 createJ2000() {
        return new J2000();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link DoubleIterval }
     * 
     */
    public DoubleIterval createDoubleIterval() {
        return new DoubleIterval();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link Filters }
     * 
     */
    public Filters createFilters() {
        return new Filters();
    }

    /**
     * Create an instance of {@link Targets }
     * 
     */
    public Targets createTargets() {
        return new Targets();
    }

    /**
     * Create an instance of {@link Constraints }
     * 
     */
    public Constraints createConstraints() {
        return new Constraints();
    }

    /**
     * Create an instance of {@link Instructions }
     * 
     */
    public Instructions createInstructions() {
        return new Instructions();
    }

    /**
     * Create an instance of {@link CameraSettings }
     * 
     */
    public CameraSettings createCameraSettings() {
        return new CameraSettings();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link PositiveDoubleIterval }
     * 
     */
    public PositiveDoubleIterval createPositiveDoubleIterval() {
        return new PositiveDoubleIterval();
    }

    /**
     * Create an instance of {@link PositiveIntegerIterval }
     * 
     */
    public PositiveIntegerIterval createPositiveIntegerIterval() {
        return new PositiveIntegerIterval();
    }

}
