//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 01:25:33 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gloria.eu/rt/entity/scheduler/plan", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.gloria.rt.entity.scheduler.plan;
