package eu.gloria.rti_scheduler;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-03-14T08:46:17.837+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "gloria_rti_scheduler", 
                  wsdlLocation = "http://localhost:8080/RTI_SCH/services/gloria_rti_schedulerSOAP?wsdl",
                  targetNamespace = "http://gloria.eu/rti_scheduler") 
public class GloriaRtiScheduler_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gloria.eu/rti_scheduler", "gloria_rti_scheduler");
    public final static QName GloriaRtiSchedulerSOAP = new QName("http://gloria.eu/rti_scheduler", "gloria_rti_schedulerSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/RTI_SCH/services/gloria_rti_schedulerSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GloriaRtiScheduler_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/RTI_SCH/services/gloria_rti_schedulerSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GloriaRtiScheduler_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GloriaRtiScheduler_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GloriaRtiScheduler_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GloriaRtiScheduler
     */
    @WebEndpoint(name = "gloria_rti_schedulerSOAP")
    public GloriaRtiScheduler getGloriaRtiSchedulerSOAP() {
        return super.getPort(GloriaRtiSchedulerSOAP, GloriaRtiScheduler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GloriaRtiScheduler
     */
    @WebEndpoint(name = "gloria_rti_schedulerSOAP")
    public GloriaRtiScheduler getGloriaRtiSchedulerSOAP(WebServiceFeature... features) {
        return super.getPort(GloriaRtiSchedulerSOAP, GloriaRtiScheduler.class, features);
    }

}
